/**
 * Type Mappers for Database <-> Domain Entity Conversion
 * Converts between snake_case database rows and camelCase TypeScript entities
 */

import type { Database } from './database.types';
import type { Member, MemberListItem, MemberStatus } from '@/core/entities/Member';
import type { Article, ArticleListItem, ArticleCategory } from '@/core/entities/Article';
import type { Event, EventListItem, EventCategory, EventStatus } from '@/core/entities/Event';
import type { Leadership, LeadershipListItem, LeadershipPosition, Division } from '@/core/entities/Leadership';

// =============================================
// MEMBER MAPPERS
// =============================================

export function dbMemberToMember(row: Database['public']['Tables']['members']['Row']): Member {
  return {
    id: row.id,
    name: row.name,
    nim: row.nim,
    email: row.email,
    phone: row.phone || undefined,
    photo: row.photo || undefined,
    batch: row.batch,
    status: row.status as MemberStatus,
    division: row.division || undefined,
    position: row.position || undefined,
    joinedAt: row.joined_at,
    graduatedAt: row.graduated_at || undefined,
    bio: row.bio || undefined,
    interests: row.interests || undefined,
    achievements: row.achievements || undefined,
    socialMedia: row.social_media ? (row.social_media as { instagram?: string; linkedin?: string }) : undefined,
  };
}

export function dbMemberToListItem(row: Database['public']['Tables']['members']['Row']): MemberListItem {
  return {
    id: row.id,
    name: row.name,
    nim: row.nim,
    photo: row.photo || undefined,
    batch: row.batch,
    status: row.status as MemberStatus,
    division: row.division || undefined,
    position: row.position || undefined,
  };
}

export function memberToDbInsert(member: Member): Database['public']['Tables']['members']['Insert'] {
  return {
    // id will be auto-generated by database (UUID)
    name: member.name,
    nim: member.nim,
    email: member.email,
    phone: member.phone || null,
    photo: member.photo || null,
    batch: member.batch,
    status: member.status,
    division: member.division || null,
    position: member.position || null,
    joined_at: member.joinedAt,
    graduated_at: member.graduatedAt || null,
    bio: member.bio || null,
    interests: member.interests || null,
    achievements: member.achievements || null,
    social_media: member.socialMedia || null,
  };
}

// =============================================
// ARTICLE MAPPERS
// =============================================

export function dbArticleToArticle(row: Database['public']['Tables']['articles']['Row']): Article {
  return {
    id: row.id,
    title: row.title,
    slug: row.slug,
    excerpt: row.excerpt,
    content: row.content,
    category: row.category as ArticleCategory,
    author: row.author as { name: string; role: string; avatar?: string },
    coverImage: row.cover_image,
    publishedAt: row.published_at,
    updatedAt: row.updated_at || undefined,
    tags: row.tags || [],
    featured: row.featured,
    views: row.views,
  };
}

export function dbArticleToListItem(row: Database['public']['Tables']['articles']['Row']): ArticleListItem {
  return {
    id: row.id,
    title: row.title,
    slug: row.slug,
    excerpt: row.excerpt,
    category: row.category as ArticleCategory,
    author: row.author as { name: string; role: string; avatar?: string },
    coverImage: row.cover_image,
    publishedAt: row.published_at,
    tags: row.tags || [],
    featured: row.featured,
    views: row.views,
  };
}

export function articleToDbInsert(
  article: Article,
  authorId: string,
  status: 'draft' | 'pending' | 'published' | 'archived' = 'draft'
): Database['public']['Tables']['articles']['Insert'] {
  return {
    // id will be auto-generated by database (UUID)
    title: article.title,
    slug: article.slug,
    excerpt: article.excerpt,
    content: article.content,
    category: article.category,
    author: article.author,
    author_id: authorId,
    cover_image: article.coverImage,
    published_at: article.publishedAt,
    tags: article.tags,
    featured: article.featured,
    status: status,
  };
}

// =============================================
// EVENT MAPPERS
// =============================================

export function dbEventToEvent(row: Database['public']['Tables']['events']['Row']): Event {
  return {
    id: row.id,
    title: row.title,
    slug: row.slug,
    description: row.description,
    content: row.content,
    category: row.category as EventCategory,
    status: row.status as EventStatus,
    startDate: row.start_date,
    endDate: row.end_date,
    location: row.location as { name: string; address: string; mapUrl?: string },
    coverImage: row.cover_image,
    images: row.images || undefined,
    organizer: row.organizer as { name: string; contact: string },
    registrationUrl: row.registration_url || undefined,
    registrationDeadline: row.registration_deadline || undefined,
    maxParticipants: row.max_participants || undefined,
    currentParticipants: row.current_participants,
    tags: row.tags || [],
    featured: row.featured,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

export function dbEventToListItem(row: Database['public']['Tables']['events']['Row']): EventListItem {
  const location = row.location as { name: string; address: string; mapUrl?: string };
  return {
    id: row.id,
    title: row.title,
    slug: row.slug,
    description: row.description,
    category: row.category as EventCategory,
    status: row.status as EventStatus,
    startDate: row.start_date,
    endDate: row.end_date,
    location: {
      name: location.name,
      address: location.address,
    },
    coverImage: row.cover_image,
    featured: row.featured,
  };
}

export function eventToDbInsert(event: Event, creatorId: string): Database['public']['Tables']['events']['Insert'] {
  return {
    // id will be auto-generated by database (UUID)
    title: event.title,
    slug: event.slug,
    description: event.description,
    content: event.content,
    category: event.category,
    status: event.status,
    start_date: event.startDate,
    end_date: event.endDate,
    location: event.location,
    cover_image: event.coverImage,
    images: event.images || null,
    organizer: event.organizer,
    creator_id: creatorId,
    registration_url: event.registrationUrl || null,
    registration_deadline: event.registrationDeadline || null,
    max_participants: event.maxParticipants || null,
    current_participants: event.currentParticipants || 0,
    tags: event.tags,
    featured: event.featured,
  };
}

// =============================================
// LEADERSHIP MAPPERS
// =============================================

export function dbLeadershipToLeadership(row: Database['public']['Tables']['leadership']['Row']): Leadership {
  return {
    id: row.id,
    name: row.name,
    position: row.position as LeadershipPosition,
    division: (row.division as Division) || undefined,
    photo: row.photo,
    email: row.email || undefined,
    phone: row.phone || undefined,
    nim: row.nim || undefined,
    batch: row.batch || undefined,
    bio: row.bio || undefined,
    socialMedia: row.social_media
      ? (row.social_media as { instagram?: string; linkedin?: string; twitter?: string })
      : undefined,
    period: {
      start: row.period_start,
      end: row.period_end,
    },
    order: row.order,
  };
}

export function dbLeadershipToListItem(row: Database['public']['Tables']['leadership']['Row']): LeadershipListItem {
  return {
    id: row.id,
    name: row.name,
    position: row.position as LeadershipPosition,
    division: (row.division as Division) || undefined,
    photo: row.photo,
    email: row.email || undefined,
    period: {
      start: row.period_start,
      end: row.period_end,
    },
    order: row.order,
  };
}

export function leadershipToDbInsert(leadership: Leadership): Database['public']['Tables']['leadership']['Insert'] {
  return {
    // id will be auto-generated by database (UUID)
    name: leadership.name,
    position: leadership.position,
    division: leadership.division || null,
    photo: leadership.photo,
    email: leadership.email || null,
    phone: leadership.phone || null,
    nim: leadership.nim || null,
    batch: leadership.batch || null,
    bio: leadership.bio || null,
    social_media: leadership.socialMedia || null,
    period_start: leadership.period.start,
    period_end: leadership.period.end,
    order: leadership.order,
  };
}
